title: GrGr 블로그
email: suojoah@gmail.com
description: |
  Connect Everything 새로운 연결, 새로운 세상.
baseur: 'https://pseudo-lab.github.io/teamgrgr'
url: ''
timezone: Asia/Seoul

repository: Pseudo-Lab/teamgrgr

permalink: /blog/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

gems:
  - jekyll-paginate

paginate: 5
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]

# iolo's custom
author: opensource@kakaocorp.com
image: '/assets/images/default_blog_cover.jpg'
asset_url: teamgrgr/assets

# google_analytics:
#   ua: 'UA-72007721-1'
github:
  username: pseudo-lab
